# Generated by Django 5.0.4 on 2024-05-06 22:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=16)),
                ('tagLine', models.CharField(max_length=5)),
                ('puuid', models.CharField(max_length=78)),
                ('summonerId', models.CharField(max_length=63)),
                ('profileIconId', models.IntegerField()),
                ('summonerLevel', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('tier', models.CharField(max_length=50)),
                ('leaguePoints', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8)),
            ],
        ),
    ]
