# Generated by Django 5.0.4 on 2024-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('gameName', models.CharField(max_length=16)),
                ('tagLine', models.CharField(default='KR1', max_length=5)),
                ('puuid', models.CharField(max_length=78)),
                ('id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('profileIconId', models.IntegerField()),
                ('summonerLevel', models.CharField(max_length=50)),
                ('rank', models.CharField(default='NONE', max_length=50)),
                ('tier', models.CharField(default=' ', max_length=50)),
                ('leaguePoints', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('matchList', models.JSONField()),
                ('matches', models.JSONField()),
                ('matchNum', models.JSONField()),
            ],
        ),
    ]
