# Generated by Django 4.2.12 on 2024-05-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=16)),
                ('tagLine', models.CharField(max_length=5)),
                ('puuid', models.CharField(max_length=78)),
                ('summonerId', models.CharField(max_length=63)),
                ('profileIconId', models.IntegerField()),
                ('summonerLevel', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('tier', models.CharField(max_length=50)),
                ('leaguePoints', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('matchList', models.JSONField()),
                ('matches', models.JSONField()),
            ],
        ),
    ]
