# Generated by Django 5.0.4 on 2024-05-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='leaguePoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rank',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='tagLine',
            field=models.CharField(default='KR1', max_length=5),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='tier',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
