# Generated by Django 5.0.4 on 2024-05-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_alter_usermodel_leaguepoints_alter_usermodel_losses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='summonerId',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(max_length=63, primary_key=True, serialize=False),
        ),
    ]
