export const lineButtons=[
    {
        name:"ALL",
        value:"all",
    },
    {
        name:"Top",
        value:"top",
    },
    {
        name:"Jungle",
        value:"jungle",
    },
    {
        name:"Mid",
        value:"mid",
    },
    {
        name:"Bottom",
        value:"bottom",
    },
    {
        name:"Support",
        value:"support",
    }
];

export const tierButtons=[
    {
        name:"IRON",
        value:"iron",
    },
    {
        name:"BRONZE",
        value:"bronze",
    },
    {
        name:"SILVER",
        value:"silver",
    },
    {
        name:"GOLD",
        value:"gold",
    },
    {
        name:"PLATINUM",
        value:"plattinum",
    },
    {
        name:"EMERALD",
        value:"emerald",
    },
    {
        name:"DIAMOND",
        value:"diamond",
    }
];