# Generated by Django 4.2.11 on 2024-06-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchInfoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_tier', models.CharField(max_length=30)),
                ('match_id', models.CharField(max_length=30)),
                ('team_id', models.CharField(max_length=5)),
                ('champion_name', models.CharField(max_length=30)),
                ('champion_id', models.CharField(max_length=30)),
                ('champion_key', models.CharField(max_length=5)),
                ('versus_name', models.CharField(max_length=30)),
                ('versus_id', models.CharField(max_length=30)),
                ('versus_key', models.CharField(max_length=5)),
                ('win', models.CharField(max_length=10)),
                ('line', models.CharField(max_length=10)),
                ('perks', models.TextField()),
                ('item', models.JSONField(default=list)),
                ('bans', models.JSONField(default=list)),
                ('match_data_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_data_version', to='main.version')),
            ],
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=10)),
                ('match_id', models.CharField(max_length=30)),
                ('match_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_version', to='main.version')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionBasicInfo',
            fields=[
                ('champ_id', models.CharField(max_length=20)),
                ('champ_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('champ_name', models.CharField(max_length=20)),
                ('champ_img', models.TextField()),
                ('champion_passive_name', models.CharField(max_length=50)),
                ('champion_passive_img', models.TextField()),
                ('champion_passive_info', models.TextField()),
                ('champion_q_name', models.CharField(max_length=50)),
                ('champion_q_img', models.TextField()),
                ('champion_q_info', models.TextField()),
                ('champion_w_name', models.CharField(max_length=50)),
                ('champion_w_img', models.TextField()),
                ('champion_w_info', models.TextField()),
                ('champion_e_name', models.CharField(max_length=50)),
                ('champion_e_img', models.TextField()),
                ('champion_e_info', models.TextField()),
                ('champion_r_name', models.CharField(max_length=50)),
                ('champion_r_img', models.TextField()),
                ('champion_r_info', models.TextField()),
                ('champ_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champ_version', to='main.version')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champion_id', models.CharField(max_length=20)),
                ('champion_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('champion_name', models.CharField(max_length=20)),
                ('champion_img', models.TextField()),
                ('champion_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_version', to='main.version')),
            ],
        ),
    ]
