# Generated by Django 4.2.12 on 2024-05-14 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champion_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('champion_name', models.CharField(max_length=20)),
                ('champion_img', models.TextField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_version', to='main.version')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionBasicInfo',
            fields=[
                ('champion_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basic_info_champion_key', serialize=False, to='main.champion')),
                ('champion_passive_name', models.CharField(max_length=25)),
                ('champion_passive_img', models.TextField()),
                ('champion_passive_info', models.TextField()),
                ('champion_q_name', models.CharField(max_length=25)),
                ('champion_q_img', models.TextField()),
                ('champion_q_info', models.TextField()),
                ('champion_w_name', models.CharField(max_length=25)),
                ('champion_w_img', models.TextField()),
                ('champion_w_info', models.TextField()),
                ('champion_e_name', models.CharField(max_length=25)),
                ('champion_e_img', models.TextField()),
                ('champion_e_info', models.TextField()),
                ('champion_r_name', models.CharField(max_length=25)),
                ('champion_r_img', models.TextField()),
                ('champion_r_info', models.TextField()),
                ('champion_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info_champion_img', to='main.champion')),
                ('champion_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info_champion_name', to='main.champion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info_version', to='main.version')),
            ],
        ),
    ]
