# Generated by Django 4.2.11 on 2024-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champ_version', models.CharField(max_length=10)),
                ('champion_id', models.CharField(max_length=20)),
                ('champion_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('champion_name', models.CharField(max_length=20)),
                ('champion_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChampionBasicInfo',
            fields=[
                ('version', models.CharField(max_length=10)),
                ('champ_id', models.CharField(max_length=20)),
                ('champ_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('champ_name', models.CharField(max_length=20)),
                ('champ_img', models.TextField()),
                ('champion_passive_name', models.CharField(max_length=25)),
                ('champion_passive_img', models.TextField()),
                ('champion_passive_info', models.TextField()),
                ('champion_q_name', models.CharField(max_length=25)),
                ('champion_q_img', models.TextField()),
                ('champion_q_info', models.TextField()),
                ('champion_w_name', models.CharField(max_length=25)),
                ('champion_w_img', models.TextField()),
                ('champion_w_info', models.TextField()),
                ('champion_e_name', models.CharField(max_length=25)),
                ('champion_e_img', models.TextField()),
                ('champion_e_info', models.TextField()),
                ('champion_r_name', models.CharField(max_length=25)),
                ('champion_r_img', models.TextField()),
                ('champion_r_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
