# Generated by Django 4.2.11 on 2024-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticsChampionMiddleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_middle_data_version', models.CharField(max_length=15)),
                ('champ_middle_data_line', models.CharField(max_length=20)),
                ('champ_middle_data_tier', models.CharField(max_length=20)),
                ('champ_middle_data_name', models.CharField(max_length=30)),
                ('champ_middle_data_img', models.CharField(max_length=30)),
                ('champ_middle_data_pick', models.CharField(max_length=10)),
                ('champ_middle_data_win', models.CharField(max_length=10)),
                ('champ_middle_data_ban', models.JSONField()),
                ('champ_middle_data_counter1', models.JSONField()),
                ('champ_middle_data_counter2', models.JSONField()),
                ('champ_middle_data_counter3', models.JSONField()),
            ],
        ),
    ]
