# Generated by Django 4.2.11 on 2024-05-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championbasicinfo',
            name='champion_e_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='championbasicinfo',
            name='champion_passive_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='championbasicinfo',
            name='champion_q_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='championbasicinfo',
            name='champion_r_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='championbasicinfo',
            name='champion_w_name',
            field=models.CharField(max_length=50),
        ),
    ]
