# Generated by Django 4.2.11 on 2024-06-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_game_version', models.CharField(max_length=15)),
                ('all_game_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ChampionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_champ_id', models.CharField(max_length=20)),
                ('detail_champ_name', models.CharField(max_length=20)),
                ('detail_win_counter_1', models.JSONField()),
                ('detail_win_counter_2', models.JSONField()),
                ('detail_win_counter_3', models.JSONField()),
                ('detail_lose_counter_1', models.JSONField()),
                ('detail_lose_counter_2', models.JSONField()),
                ('detail_lose_counter_3', models.JSONField()),
                ('detail_rune_1', models.JSONField()),
                ('detail_rune_2', models.JSONField()),
                ('detail_skill_master', models.JSONField()),
                ('detail_skill_build', models.JSONField()),
                ('detail_spell', models.JSONField()),
                ('detail_start', models.JSONField()),
                ('detail_shoes', models.JSONField()),
                ('detail_item_build', models.JSONField()),
                ('detail_use_legend', models.JSONField()),
            ],
        ),
    ]
