# Generated by Django 4.2.11 on 2024-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staticschampionmiddledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticschampionmiddledata',
            name='champ_middle_data_pick',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='staticschampionmiddledata',
            name='champ_middle_data_win',
            field=models.CharField(max_length=30),
        ),
    ]
