# Generated by Django 4.2.11 on 2024-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_championbasicinfo_champion_e_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInfoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=30)),
                ('team_id', models.CharField(max_length=5)),
                ('champion_name', models.CharField(max_length=30)),
                ('champion_id', models.CharField(max_length=30)),
                ('versus_name', models.CharField(max_length=30)),
                ('versus_id', models.CharField(max_length=30)),
                ('win', models.CharField(max_length=10)),
                ('line', models.CharField(max_length=10)),
                ('perks', models.TextField()),
                ('item0', models.CharField(max_length=5)),
                ('item1', models.CharField(max_length=5)),
                ('item2', models.CharField(max_length=5)),
                ('item3', models.CharField(max_length=5)),
                ('item4', models.CharField(max_length=5)),
                ('item5', models.CharField(max_length=5)),
                ('item6', models.CharField(max_length=5)),
            ],
        ),
    ]
