# Generated by Django 4.2.11 on 2024-06-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allgamedata_championdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStaticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statics_tier', models.CharField(max_length=15)),
                ('statics_position', models.CharField(max_length=15)),
                ('statics_ranking', models.CharField(max_length=10)),
                ('statics_champ_name', models.CharField(max_length=20)),
                ('statics_champ_img', models.CharField(max_length=20)),
                ('statics_champ_id', models.CharField(max_length=20)),
                ('statics_play', models.CharField(max_length=20)),
                ('statics_kda', models.CharField(max_length=20)),
                ('statics_win', models.CharField(max_length=20)),
                ('statics_pick', models.CharField(max_length=20)),
                ('statics_ban', models.CharField(max_length=20)),
                ('statics_cs', models.CharField(max_length=20)),
                ('statics_gold', models.CharField(max_length=20)),
            ],
        ),
    ]
