# Generated by Django 4.2.11 on 2024-05-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_matchinfodata_item0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfodata',
            name='item',
            field=models.JSONField(default=list),
        ),
    ]
