# Generated by Django 4.2.11 on 2024-05-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_matchinfodata_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfodata',
            name='champion_key',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchinfodata',
            name='versus_key',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
