# Generated by Django 4.2.11 on 2024-05-20 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_matchinfodata_champion_key_matchinfodata_versus_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='champ_version',
        ),
        migrations.RemoveField(
            model_name='championbasicinfo',
            name='version',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='id',
        ),
        migrations.AddField(
            model_name='champion',
            name='champion_version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='champion_version', to='main.version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championbasicinfo',
            name='champ_version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='champ_version', to='main.version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchdata',
            name='match_version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='match_version', to='main.version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchdata',
            name='tier',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchinfodata',
            name='match_data_version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='match_data_version', to='main.version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='match_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
