# Generated by Django 4.2.11 on 2024-05-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_champion_champ_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfodata',
            name='bans',
            field=models.JSONField(default=list),
        ),
    ]
