# Generated by Django 4.2.11 on 2024-06-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlexRankModel',
            fields=[
                ('gameName', models.CharField(max_length=16)),
                ('tagLine', models.CharField(default='KR1', max_length=5)),
                ('puuid', models.CharField(max_length=78)),
                ('id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('profileIconId', models.IntegerField()),
                ('summonerLevel', models.CharField(max_length=50)),
                ('rank', models.CharField(default='NONE', max_length=50)),
                ('tier', models.CharField(default=' ', max_length=50)),
                ('leaguePoints', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SoloRankModel',
            fields=[
                ('gameName', models.CharField(max_length=16)),
                ('tagLine', models.CharField(default='KR1', max_length=5)),
                ('puuid', models.CharField(max_length=78)),
                ('id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('profileIconId', models.IntegerField()),
                ('summonerLevel', models.CharField(max_length=50)),
                ('rank', models.CharField(default='NONE', max_length=50)),
                ('tier', models.CharField(default=' ', max_length=50)),
                ('leaguePoints', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
    ]
