# Generated by Django 4.2.11 on 2024-06-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexrankmodel',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solorankmodel',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
